### ISSUE TITLE
read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by reverse28** [kai-morich/SimpleBluetoothTerminal#1]
Connection failed: read failed, socket might closed or timeout, read ret: -1   Hi. I get this error every time when I try to connect to a mobile device and sometimes when I try to connect to a PC. It helps to restart the PC, but this is not a solution to the problem. I have limited communication between the PC and the smartphone via the COM-port. Do you have any idea why this is happening? I tested the software on many devices and everywhere the same result.

**Comment by kai-morich** [comment]
the android bluetooth error codes are basically useless, so it's very difficult to find out the real issue
