### ISSUE TITLE
hc-06 connection failed

### ISSUE THREAD

**Issue by Ardminu** [kai-morich/SimpleBluetoothTerminal#11]
First I would like to thank you for sharing this code. I have tried to use it with Bluetooth module HC-06, which is a 2.x technology. 
But I keep getting 
" connecting .. 
connection failed: read failed, socket might closed or timeout, read ret:-1"

However, when using your Serial Bluetooth Terminal app, it gets connected normally without any issue.

Any suggestion to overcome this probelm?

**Comment by Ardminu** [comment]
issue resolved by this change:
//socket = device.createRfcommSocketToServiceRecord(BLUETOOTH_SPP);
  socket = device.createInsecureRfcommSocketToServiceRecord(BLUETOOTH_SPP);

**Comment by kai-morich** [comment]
strange. my Serial Bluetooth Terminal app also uses createRfcommSocketToServiceRecord
