### ISSUE TITLE
How send hex 

### ISSUE THREAD

**Issue by mariliahoshino** [kai-morich/SimpleBluetoothTerminal#14]
I'd like send hex data instead ASCII 
In your app in play store is possible, but in simple Bluetooth terminal no

I'll use a can analyser for maintenance of machine 

Tks

![20201011_000952](https://user-images.githubusercontent.com/62081861/95678879-b0e15980-0ba5-11eb-9082-3972d9bd6d0d.jpg)

![Screenshot_20201011-000930_Serial Bluetooth Terminal](https://user-images.githubusercontent.com/62081861/95678884-bfc80c00-0ba5-11eb-897d-342f2ad65aae.jpg)

**Comment by harryberlin** [comment]
what's the issue. the app of released source is an simple example.
i think, if you need some more functionallity, you can add by yourself.

**Comment by mariliahoshino** [comment]
How send in HEX?, I don't have idea yet

**Comment by harryberlin** [comment]
hex is just an option to make values visible.
0xFF ist the same like 255 or 0b11111111
if you want send an hex string as value, you have to convert (string to integer) before.

**Comment by kai-morich** [comment]
see 95b45f70f08496bbbd7a96f4afd4fffc799c4b7e
