### ISSUE TITLE
Receive data when lock screen

### ISSUE THREAD

**Issue by hominh** [kai-morich/SimpleBluetoothTerminal#19]
Hi.
I am using your code. How to receive data when lock screen.
Thanks you very much

**Comment by kai-morich** [comment]
Data is received by `SerialService` class while screen is locked or App is in minimized. When the App gets visible again, the `TerminalFragment` gets all accumulated data after `service.attach()`.
If you want to process data while screen is locked or App is in minimized, you have to do this in a foreground service like `SerialService`.

**Comment by hominh** [comment]
Thanks you for reply. How to modify SerialService class to process data while screen is locked?

**Comment by kai-morich** [comment]
see `onSerialRead` method where `listener == null`
