### ISSUE TITLE
Connection always fails on Android API 28

### ISSUE THREAD

**Issue by OuterObsessionSoftware** [kai-morich/SimpleBluetoothTerminal#2]
I've been recently working on a app based on your SimpleBluetoothTerminal example and it works really well.

I've started to do testing on a range of devices and noticed something strange. On one of our devices (Samsung S8 API 28) it fails to establish a connection. I tried loading up the unmodified example and the Google Play version with identical results.

The only thing I haven't been able to test is if the failed connection is specific to certain Bluetooth devices or all Bluetooth devices.

Did they change the way Bluetooth operates in 28? I know in Android Q they're making big changes to the Bluetooth stack. It's not a big deal at all just thought that was kinda strange.

**Comment by kai-morich** [comment]
I im not aware of changes with API 28. On test devices everything works as before

**Comment by Chuntianhong** [comment]
I also have a same issue.
It doesn't connect in Android 9 device(API 29).
With same app, connect to Android 7,

```
socket = device.createRfcommSocketToServiceRecord(BLUETOOTH_SPP);
socket.connect();
```
In connect() function, it gives exception.
Would you give me any suggestion?
