### ISSUE TITLE
how Change buard rate to 9600

### ISSUE THREAD

**Issue by vudugundlasathish** [kai-morich/SimpleBluetoothTerminal#20]

**Comment by kai-morich** [comment]
There is no baud rate on bluetooth side. If you have connected a bluetooth to serial module like HC05 you can set its baud rate from serial side with AT command

**Comment by vudugundlasathish** [comment]
OK thanks for your reply I have bluetooth device IOGEAR with model no : GBC232A i want to change baud rate of this device to 9600 How to change this by AT command ?

**Comment by harryberlin** [comment]
> 
> 
> OK thanks for your reply I have bluetooth device IOGEAR with model no : GBC232A i want to change baud rate of this device to 9600 How to change this by AT command ?

you should try to request google in case of your issue.

**Comment by kai-morich** [comment]
From GBC232A quick start guide looks like you have to connect to a Windows PC initially and use vendor tool to configure the device
