### ISSUE TITLE
Double key entry

### ISSUE THREAD

**Issue by mpevner** [kai-morich/SimpleBluetoothTerminal#21]
This is presumably more for the published on on Google, but hopefully appropriate here: I've noticed when using a bluetooth keyboard that hitting Enter causes a double entry. Presumably as in [0] it is reading both they key down and key up events. Interestingly, this does not occur with on-screen keyboards. Text input is not affected, presumably due to using a text box instead.

[0] https://github.com/onyxbits/TextFiction/issues/17

**Comment by kai-morich** [comment]
thanks for that info. With that I could now reproduce this issue.

**Comment by kai-morich** [comment]
fixed for my apps published at Google
