### ISSUE TITLE
Received text formatting

### ISSUE THREAD

**Issue by sv-pizzazz** [kai-morich/SimpleBluetoothTerminal#32]
Is it possible to add some basic received text formatting? It would be useful to control various devices. For example, I am using it to control an HF radio. When I send a macro to change the frequency, the radio responds with: 

$PSEAR,15,03674000,0367400,0,0*AC

I would like to format and display this as:

Freq: 3.674 MHz

Thank you.

**Comment by kai-morich** [comment]
I want to keep this app as a simple example, so basically only bugs are fixed, but features are unlikely to be added. 
Feel free to add your domain specific formatting in your fork.
