### ISSUE TITLE
Please post a compiled APK so I  can sideload it

### ISSUE THREAD

**Issue by RoadsterMan** [kai-morich/SimpleBluetoothTerminal#35]
Please post a compiled APK so I  can sideload it. I'm using it in an industrial environment

**Comment by kai-morich** [comment]
please build your own APK in Android Studio

**Comment by RoadsterMan** [comment]
Ty, I found another site that had it for download.
It's wonderful ty! 👍


Walter Peterson
(805)689-7557 mobile
