### ISSUE TITLE
Icon indicating logging has been set and it is running well

### ISSUE THREAD

**Issue by igor-m** [kai-morich/SimpleBluetoothTerminal#36]
Hi Kai, I've been using your android version (the latest) for logging data from an mcu and it happened many times I forgot to switch on the logging ticker, thus I lost the data. Would be great to indicate in the top bar with an icon the logging was set and it is actually running and has not been interrupted. 
Thanks!

**Comment by kai-morich** [comment]
available with:
1.45 2023-06-18
NEW show active logging in toolbar

**Comment by igor-m** [comment]
Thanks!
