### ISSUE TITLE
About transmitting data from Serial Bluetooth Terminal app to arduino due

### ISSUE THREAD

**Issue by JMJ15** [kai-morich/SimpleBluetoothTerminal#4]
Sir, When ever I try to  pass any character from Serial Bluetooth Terminal app it is not working. But when I try to pass the character from serial monitor of Arduino it is transmitting to serial monitor and  also to phone via Bluetooth. From that thing I understood that receiving data from Arduino via Bluetooth to phone is working but transmitting data from phone to Arduino is not working. Hereby attaching the code what I used in Arduino side. 

char Incoming_value = 0; 
void setup()
{
  Serial.begin(9600);    
  pinMode(LED_BUILTIN, OUTPUT);     
}
void loop()
{
  if (Serial.available() > 0)
  {
    digitalWrite(LED_BUILTIN, HIGH);
    Incoming_value = Serial.read(); 
    Serial.write(Incoming_value);
    delay(500);
    digitalWrite(LED_BUILTIN, LOW); 
  }

Hopefully waiting for your help and thanks in advance.

**Comment by kai-morich** [comment]
please check https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#i-am-using-an-arduino-uno-sparkfun-pro-micro-or-other-arduino-and-if-serial-doesnt-work

**Comment by JMJ15** [comment]
Sir with OTG its working fine. But when I replace OTG with HC-05 Bluetooth module transmission is not working but receiving side is okay. I came to this conclusion by checking it with serial monitor in arduino in PC

**Comment by JMJ15** [comment]
Thanks a lot I corrected it. Its because i did not used the other serial port available in due. When I used other Rx & Tx (1 or 2 or 3) it works fine.
Thanks anyway
