### ISSUE TITLE
Error in sending long string through the app

### ISSUE THREAD

**Issue by Anshullanjewar** [kai-morich/SimpleBluetoothTerminal#42]
I want to send a long string with 108 characters to my Bluetooth module String is (101122000000000030250130280000000000000000000000001000183000000000000000000000000000211000200011000001200000) but i am getting string as (100003025013028000000000000000000000000100018300000000000000000000000000021100020001100000120000000000000000) Help me to send the correct data from this terminal to the HC05 .

**Comment by kai-morich** [comment]
maybe reading the serial data from HC05 isn't fast enough

**Comment by Anshullanjewar** [comment]
I am still facing an issue, I want to send 500 characters from terminal but after 120 characters it start receiving random values.
