### ISSUE TITLE
Terminal does not work as a foreground service

### ISSUE THREAD

**Issue by babylon73** [kai-morich/SimpleBluetoothTerminal#46]
Hi,

There is a permission android.permission.FOREGROUND_SERVICE in the manifest - but SerialService stops working as soon as we switch to another application.

Would be great to make the work of the terminal continuous - so it could handle the incoming data even when user is in some other application.

Thank you!

**Comment by kai-morich** [comment]
The app / service continues to work if it is not in the foreground, see [SerialService#L24](https://github.com/kai-morich/SimpleBluetoothTerminal/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fde%2Fkai_morich%2Fsimple_bluetooth_terminal%2FSerialService.java#L24)
